name: Auto Merge Main to Testing

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: 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 # Use the PAT here

      - name: Configure Git
        run: |
          git config --global user.name 'Abhishek-BG'
          git config --global user.email 'abhigowda0190@gmail.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into testing
        run: |
          git checkout testing
          git merge -X theirs main --allow-unrelated-histories
          git push origin testing
